{% set name = "ncephes" %}
{% set version = "1.0.40" %}
{% set sha256 = "0ec665b003714117fd84f59af51361165f6ff58cc7822d31e07b1902ec1da9de" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: True  # [win32 or linux32 or (win64 and py27)]
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
    - pytest-runner
    - build-capi
    - cffi >=1.7
    - pycparser
    - toolchain
  run:
    - python
    - cffi >=1.7

test:
  requires:
    - pytest >=3
    - numpy
  imports:
    - ncephes
  commands:
    - python -c "import sys; import ncephes; sys.exit(ncephes.test())"

about:
  home: https://github.com/limix/ncephes
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Python interface for the Cephes library'
  doc_url: https://ncephes.readthedocs.io
  dev_url: https://github.com/limix/ncephes

extra:
  recipe-maintainers:
    - Horta
