{% set name = "ncephes" %}
{% set version = "1.1.0" %}
{% set sha256 = "0a375e942e48fbdde28ec9c7a74f4fa6d3cbaea8ace3cc8cc3da5a6f3b2db9c2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1005
  skip: True  # [win and vc<14]
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - pip
    - python
    - setuptools
    - pytest-runner
    - cffi >=1.7
    - hcephes >=0.3.3
  run:
    - python
    - cffi >=1.7
    - hcephes >=0.3.3
    - numpy

test:
  requires:
    - pytest >=3
    - numpy
  imports:
    - ncephes
  commands:
    - python -c "import sys; import ncephes; sys.exit(ncephes.test())"

about:
  home: https://github.com/limix/ncephes
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Python interface for the Netlib Cephes library'
  doc_url: https://ncephes.readthedocs.io
  dev_url: https://github.com/limix/ncephes

extra:
  recipe-maintainers:
    - Horta
