travis:
  secure:
    BINSTAR_TOKEN: bW+uhoF3WuMWynvh5XckeiTyU8zkLXoBdcqOgBTxikKQWBWAZvwLnvLXjU1m0gztJuB2A53xe+C2u0w3AlfyBSWfFeK7fdWvyoU59PPjm8omUvSHwBMVAL4P1CP636JOnohsgvXKY0s+fLNWxWF7uOwhOJbTHhNdTZYeCySdi+RsX3pLNHaphCpGCQF9nk7FZtMhPSgACTEf3KvangNfG5GFWCslkLBQP+CDevXHx1qwvKN/yKOTPxu8uvGF+vyCYlBmKxzArsGjlnOdVGjAuAfZQWYtx+kSkCy5OFmLofmbsgRGsD+3m1rVe8MM0Szvoi6FaMixlY5jCmTAE8ix/DqZcKRCYhiUUsVRWSS0AM/t6OqSah8u2a039u0pt8SNODBEoSI6eNt/sxBsQeLWyOEzBzvAABfJF1YbWtFQ1w033Ov1BFw+0Ttdk/6as9Vicu+74JUoMnIEAB8TyDy2kzJZOOnVmhq+JHvNWMn7P+G8WZ/RbqlRNPlK5OhcngrnobOnoUrRszDILjM5k3zwhkhc8XolveKtEGdvu/IpM1x3FKlpOJI8c1SWzlyA/sYcAZKk1XjgtoWo2Df7eiiIPFKE/5ZXbssKxlBZ87cFGkMyXw4FCyY3C9jataGlqtoTSVk+4dsVY8TewbcbtaWKd5UkTipJ3iN0q1rQ9RZ5I0U=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
